"""add priority weights to companies

Revision ID: 95021f2e127e
Revises: d77cb697918a
Create Date: 2026-07-25 18:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95021f2e127e'
down_revision: Union[str, None] = 'd77cb697918a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_amount', sa.Numeric(precision=10, scale=4), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('weight_idle', sa.Numeric(precision=10, scale=4), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('weight_stage', sa.Numeric(precision=10, scale=4), nullable=False, server_default='8'))
        batch_op.add_column(sa.Column('weight_overdue_task', sa.Numeric(precision=10, scale=4), nullable=False, server_default='15'))
        batch_op.add_column(sa.Column('weight_multi_rule', sa.Numeric(precision=10, scale=4), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('weight_multi_rule')
        batch_op.drop_column('weight_overdue_task')
        batch_op.drop_column('weight_stage')
        batch_op.drop_column('weight_idle')
        batch_op.drop_column('weight_amount')

    # ### end Alembic commands ###
