"""init schema

Revision ID: d0ae22573b74
Revises: 
Create Date: 2026-07-25 15:59:30.582216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ae22573b74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'external_id', name='uq_contact_external')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_external_id'), ['external_id'], unique=False)

    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('applies_to_stage_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_rule_company_code')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_company_id'), ['company_id'], unique=False)

    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_closed_won', sa.Boolean(), nullable=False),
    sa.Column('is_closed_lost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stages_company_id'), ['company_id'], unique=False)

    op.create_table('report_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('leads_no_response', sa.Integer(), nullable=False),
    sa.Column('deals_stalled', sa.Integer(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recommendations_completed', sa.Integer(), nullable=False),
    sa.Column('deals_reactivated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_snapshots_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('csv_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csv_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_imports_company_id'), ['company_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=True),
    sa.Column('next_contact_date', sa.DateTime(), nullable=True),
    sa.Column('last_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'external_id', name='uq_deal_external')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_external_id'), ['external_id'], unique=False)

    op.create_table('deal_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_stage_history_deal_id'), ['deal_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('priority_breakdown_json', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=50), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_deal_id'), ['deal_id'], unique=False)

    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_log_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_log_deal_id'), ['deal_id'], unique=False)

    op.create_table('daily_digest_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_digest_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_digest_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_digest_items_user_id'), ['user_id'], unique=False)

    op.create_table('deal_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_tasks_deal_id'), ['deal_id'], unique=False)

    op.create_table('message_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_drafts_recommendation_id'), ['recommendation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_drafts_recommendation_id'))

    op.drop_table('message_drafts')
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_tasks_deal_id'))

    op.drop_table('deal_tasks')
    with op.batch_alter_table('daily_digest_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_digest_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_digest_items_company_id'))

    op.drop_table('daily_digest_items')
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_deal_id'))
        batch_op.drop_index(batch_op.f('ix_action_log_company_id'))

    op.drop_table('action_log')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_deal_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('deal_stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_stage_history_deal_id'))

    op.drop_table('deal_stage_history')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_external_id'))
        batch_op.drop_index(batch_op.f('ix_deals_company_id'))

    op.drop_table('deals')
    with op.batch_alter_table('csv_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_imports_company_id'))

    op.drop_table('csv_imports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('report_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_snapshots_company_id'))

    op.drop_table('report_snapshots')
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_company_id'))

    op.drop_table('pipeline_stages')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_company_id'))

    op.drop_table('detection_rules')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_external_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    op.drop_table('companies')
    # ### end Alembic commands ###
