"""add external_id to deal_tasks

Revision ID: d77cb697918a
Revises: d0ae22573b74
Create Date: 2026-07-25 17:21:53.115193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77cb697918a'
down_revision: Union[str, None] = 'd0ae22573b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_deal_tasks_external_id'), ['external_id'], unique=False)
        batch_op.create_unique_constraint('uq_task_deal_external', ['deal_id', 'external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_deal_external', type_='unique')
        batch_op.drop_index(batch_op.f('ix_deal_tasks_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
